/*
El siguiente codigo crea una base de datos, no se puede crear mas de una con el mismo nombre
CREATE DATABASE [DATA ANALITYCS 57445]

La puedo eliminar con el siguinte codigo:
DROP DATABASE [DATA ANALITYCS 57445]

CREATE TABLE Clientes (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE VARCHAR(60) NOT NULL,
	CUIL VARCHAR(13) NOT NULL UNIQUE CHECK(CUIL LIKE '[0-9][0-9]-[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]-[0-9]'),
	DIRECCION VARCHAR(70) NOT NULL,
	CIUDAD VARCHAR(30) NOT NULL,
	PROVINCIA TEXT NOT NULL,
	MAIL VARCHAR(35) NOT NULL UNIQUE CHECK (MAIL LIKE '%_@__%.__%'),
	TELEFONO INT UNIQUE CHECK (TELEFONO > 0),
	[FECHA ALTA] DATE NOT NULL DEFAULT GETDATE(),
	TC BIGINT UNIQUE);


CREATE TABLE Vendedores (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	[NOMBRE COMPLETO] TEXT NOT NULL,
	[FECHA NACIMIENTO] DATE NOT NULL
	CHECK (DATEDIFF(YEAR, [FECHA NACIMIENTO], GETDATE()) >=18),
	[FECHA CONTRATACION] DATE NOT NULL DEFAULT GETDATE() CHECK([FECHA CONTRATACION] <= GETDATE()),
	CUIL VARCHAR(13) NOT NULL UNIQUE CHECK(CUIL LIKE '[0-9][0-9]-[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]-[0-9]'),
	DIRECCION VARCHAR(60) NOT NULL,
	CIUDAD VARCHAR(35) NOT NULL,
	PROVINCIA TEXT NOT NULL DEFAULT 'Buenos Aires',
	MAIL VARCHAR(35) NOT NULL UNIQUE CHECK (MAIL LIKE '%_@__%.__%'),
	TELEFONO INT UNIQUE CHECK (TELEFONO > 0),
	EDAD TINYINT NOT NULL CHECK(EDAD >= 18));


CREATE TABLE Ventas (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	[ID CLIENTE] INT NOT NULL,
	[ID VENDEDOR] INT NOT NULL,
	FECHA DATE NOT NULL DEFAULT GETDATE(),
	TOTAL MONEY NOT NULL CHECK(TOTAL >0),
	CONSTRAINT FK_CLIENTES FOREIGN KEY ([ID CLIENTE]) REFERENCES Clientes (ID),
	CONSTRAINT FK_VENDEDORES FOREIGN KEY ([ID VENDEDOR]) REFERENCES Vendedores (ID)
);


SELECT *
FROM 
    Ventas
INNER JOIN 
    Clientes ON Ventas.[ID CLIENTE] = Clientes.ID
INNER JOIN 
    Vendedores ON Ventas.[ID VENDEDOR] = Vendedores.ID;
/*